### PR TITLE
Min Product Value

### PR DESCRIPTION
**Pull request by pikachu1992**
- LPPR add min flight departures and arrivals 
- LPPR get scenario from runway 35 and 17
- LPPT get scenario from runway 03 and 21
- Airport altitudes are fixed to airports above
- Get airport HOLDS from runway choice
- Delay START is works by spawn point

### CODE REVIEW

**Comment by pikachu1992** [comment]
LPFR - min arrivals added

in fault: LPFR stands

**Comment by pikachu1992** [comment]
LPFR stands added

**Comment by pikachu1992** [comment]
LPMA add init data

**Comment by pedro2555** [comment]
Check PR #32

**Pull request closed without merging**
